append_commit_message: false
commit_message: '[ci skip] New %language% translation from Crowdin'
files:
- source: /jupyterlab/locale/jupyterlab.pot
  translation: /jupyterlab/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po
