append_commit_message: false
commit_message: '[ci skip] New %language% translation from Crowdin'
files:
- source: /jupyterlab/locale/jupyterlab.pot
  translation: /jupyterlab/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po
- source: /extensions/dask_labextension/locale/dask_labextension.pot
  translation: /extensions/dask_labextension/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po
- source: /extensions/jupyterlab_git/locale/jupyterlab_git.pot
  translation: /extensions/jupyterlab_git/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po
