name: Prepare language packs for release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version with format 'X.Y.postZ'"
        required: false
        default: ''

permissions:
  contents: write

jobs:
  prepare_release:
    runs-on: ubuntu-latest

    env:
      TARGET_VERSION: ${{ github.event.inputs.version }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/release.txt
          # temporarily use master version as not yet released
          python -m pip install git+https://github.com/jupyterlab/jupyterlab-translate
      - name: Update the language packages
        if: ${{ github.event.inputs.version == '' }}
        run: |
          python scripts/03_prepare_release.py
      - name: Update the language packages
        if: ${{ github.event.inputs.version != '' }}
        run: |
          python scripts/03_prepare_release.py --new-version "${{ github.event.inputs.version }}"
      - name: Set branch name and get hash
        run: |
          echo "BRANCH_NAME=pack-update-${VERSION:-auto}" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Create a new branch
        run: |
          git checkout -b "${{ env.BRANCH_NAME }}"
      - name: Set up git identity
        run: |
          git config user.name "JupyterLab Language Packs Bot"
          git config user.email 'jupyterlab-bot@users.noreply.github.com'
      - name: Commit changes
        run: |
          git add language-packs
          git commit -m "Update language packs"
      - name: Push the changes
        run: |
          git push --set-upstream origin "${{ env.BRANCH_NAME }}"
      - name: Create a PR
        run: |
          hub pull-request -m "Update language packs to '${VERSION:-auto}'"
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

